---
language: node_js
node_js:
  - "node"

cache:
  directories:
    - node_modules

before_install:
  - sudo apt-get install phantomjs -y
  - npm config set spin false
  - npm install -g npm@^2

install:
  - npm install -g bower
  - npm install -g ember
  - npm install
  - bower install
  - ember build -prod

script:
  - npm test
